# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyRangePal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyRangePal
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.3.0'

  target 'MyRangePalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MyRangePal-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyRangePal-tvOS

  target 'MyRangePal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
